/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './directives';
export const CreditCardDirectivesModuleNgFactory:i0.NgModuleFactory<i1.CreditCardDirectivesModule> = i0.ɵcmf(i1.CreditCardDirectivesModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,
          i1.CreditCardDirectivesModule,i1.CreditCardDirectivesModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvc3RldmVuL1Byb2plY3RzL2FuZ3VsYXItY2MtbGlicmFyeS9zcmMvZGlyZWN0aXZlcy5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL3N0ZXZlbi9Qcm9qZWN0cy9hbmd1bGFyLWNjLWxpYnJhcnkvc3JjL2RpcmVjdGl2ZXMudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OzsifQ==
