name: release

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write # Required for npm trusted publishing

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies and build
        run: |
          yarn install
          yarn build:library

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: npm config
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: Bump version
        run: npx release-it --increment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
